spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
  application:
    name: pedido-service
server:
  port: 8080
app:
  sns:
    topic-arn: ${SNS_TOPIC_ARN}
  sqs:
    queue-name: ${QUEUE_NAME}